Added stickbugparrot.gif and added description lol
jmhobbs/cultofthepartyparrot.com pull request #611
Opened 2022-10-18 09:44 UTC by OliverVermeulen

2022-10-18 14:37 UTC, jmhobbs commented
Did that do what you intended?  I don't see a stickbugparrot.gif in the files, only a mongodb logo parrot.

2022-10-18 17:19 UTC, OliverVermeulen commented
Hello John, I removed the stickbugparrot.gif as it was to big and didn't
really fit with the tone of Party Parrot so I added the mongodbparrot.gif

Thank you
Oliver

On Tue, 18 Oct 2022, 16:37 John Hobbs, ***@***.***> wrote:

> Did that do what you intended? I don't see a stickbugparrot.gif in the
> files, only a mongodb logo parrot.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jmhobbs/cultofthepartyparrot.com/pull/611#issuecomment-1282500896>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARG2BWJ2RBLDP4FDWT6TXR3WD2Y2BANCNFSM6AAAAAARH4QAKQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-19 14:44 UTC, jmhobbs requested changes

2022-10-19 14:44 UTC, jmhobbs commented on parrots.yaml
> +  name: MongoDB Parrot
Can you pop a newline at the end of the file here?  Thanks!

2022-10-19 14:47 UTC, jmhobbs commented
Perhaps consider putting the logo behind the parrot in the style of these other logo parrots?
![https://cultofthepartyparrot.com/parrots/hd/reactparrot.gif](https://cultofthepartyparrot.com/parrots/hd/reactparrot.gif)![https://cultofthepartyparrot.com/parrots/hd/innersourceparrot.gif](https://cultofthepartyparrot.com/parrots/hd/innersourceparrot.gif)![https://cultofthepartyparrot.com/parrots/hd/phparrot.gif](https://cultofthepartyparrot.com/parrots/hd/phparrot.gif)

2022-10-19 17:09 UTC, jmhobbs commented
Amazing! Thank you for your contribution!

2022-10-19 17:10 UTC, merged